### ISSUE TITLE
Login requires Captcha

### ISSUE THREAD

**Issue by AndreasTusche** [markwiesemann/moneymoney-deutschlandcard#1]
The first attempt to connect to the DeutschlandCard Account required to white-list an SHA256 fingerprint and then all further attempts require a Captcha that is not shown via the Money Money Interface, hence cannot be done. Creating a new Money Money account based on the DeutschlandCard Number and PIN does not work. (PS: yes I tried the PIN on their web-page and I was using the correct one, just if you wonder...)

Here is the protocoll from Money Money:

~~~
22:22:52  Starting account setup assistant.
22:23:56  Lade Kontenliste ...
          Web Banking Engine: Using user-supplied extension Deutschlandcard-Punkte.lua version 1.10.
          Protocol version: Web Scraping
          Server address: https://www.deutschlandcard.de/
          Loading captcha: https://www.recaptcha.net/recaptcha/api.js?render=6Le2S9AUAAAAAD4SMzwje15-swuVJtwV9O1HyL9T
22:23:57  Submitting login form.
          Sending: POST https://www.deutschlandcard.de/api/v1/auth/connect/token
22:24:03  Unknown SSL certificate for https://www.deutschlandcard.de/.
          SHA256 fingerprint: E2:43:49:2E:9B:C9:D0:FE:16:2A:C0:B4:16:A3:B6:9D:F9:32:03:D6:A7:64:CB:A1:DA:8E:F4:F9:F6:91:FE:BC
          SHA1 fingerprint: F3:CB:DC:CD:3F:06:44:F3:F4:F4:91:99:BE:0C:D4:2F:BE:16:45:90
          Requesting SSL certificate whitelist from MoneyMoney web service: https://service.moneymoney-app.com/
          SSL certificate is not whitelisted.
          Asking user to verify SSL certificate.
22:24:17  HTTPS response: HTTP/1.1 400 Bad Request
          Received: {"status":"ERROR","statusCode":400,"data":{"message":"Request failed with status code 400","error":"invalid_grant","error_description":"invalid credential","bot-detection-error":"InvalidScoreCaptchaV3"}}
          Response: invalid credential
          Ihre Zugangsdaten (Kartennummer, PIN) wurden vom Server Ihrer Bank als ungültig abgewiesen. Bitte überprüfen Sie noch einmal Ihre Zugangsdaten.
~~~

**Comment by AndreasTusche** [comment]
Interestingly fetching the account balance works once but only when I am already logged-in via the webpage. Else I am still running in almost the same problems. The SHA256 fingerprint is no longer requested but everything else fails. Here is my most recent protocol from Money Money (2.3.33):

~~~
19:09:31  1> Starting Web Banking session for account DeutschlandCard.
          1> Web Banking Engine: Using user-supplied extension Deutschlandcard-Punkte.lua version 1.10.
          1> Protocol version: Web Scraping
          1> Server address: https://www.deutschlandcard.de/
          1> Asking user for password.
19:09:36  1> Loading captcha: https://www.recaptcha.net/recaptcha/api.js?render=6Le2S9AUAAAAAD4SMzwje15-swuVJtwV9O1HyL9T
19:09:40  1> Submitting login form.
          1> Sending: POST https://www.deutschlandcard.de/api/v1/auth/connect/token
          1> HTTPS response: HTTP/1.1 400 Bad Request
          1> Received: {"status":"ERROR","statusCode":400,"data":{"message":"Request failed with status code 400","error":"invalid_grant","error_description":"invalid credential","bot-detection-error":"InvalidScoreCaptchaV3"}}
          1> Response: invalid credential
          1> Login failed, asking user for password.
19:11:26  1> Loading captcha: https://www.recaptcha.net/recaptcha/api.js?render=6Le2S9AUAAAAAD4SMzwje15-swuVJtwV9O1HyL9T
19:11:29  1> Submitting login form.
          1> Sending: POST https://www.deutschlandcard.de/api/v1/auth/connect/token
          1> HTTPS response: HTTP/1.1 400 Bad Request
          1> Received: {"status":"ERROR","statusCode":400,"data":{"message":"Request failed with status code 400","error":"invalid_grant","error_description":"invalid credential","bot-detection-error":"InvalidScoreCaptchaV3"}}
          1> Response: invalid credential
          1> Ihre Zugangsdaten (Kartennummer, PIN) wurden vom Server Ihrer Bank als ungültig abgewiesen. Bitte überprüfen Sie noch einmal Ihre Zugangsdaten.
~~~

**Comment by markwiesemann** [comment]
Sorry, I didn't get a notification about your initial report from June.
I'll have a look at the issue soon.

**Comment by markwiesemann** [comment]
Andreas, could you please send me your email address? (post at mark minus wiesemann dot de, in German, "Du" if you want)
I'd like to understand the recaptcha.net response that you're getting.

**Comment by AndreasTusche** [comment]
Hi Mark, I just did a clean update of my Mac OS from High Sierra to Catalina and now it works, although I do not understand why it works. The recaptcha.net query is still there but this time I correctly received an access token.

~~~
20:55:51  1> Starting Web Banking session for account DeutschlandCard.
          1> Web Banking Engine: Using user-supplied extension Deutschlandcard-Punkte.lua version 1.10.
          1> Protocol version: Web Scraping
          1> Server address: https://www.deutschlandcard.de/
          1> Asking user for password.
20:56:34  1> Loading captcha: https://www.recaptcha.net/recaptcha/api.js?render=6Le2S9AUAAAAAD4SMzwje15-swuVJtwV9O1HyL9T
20:56:36  1> Submitting login form.
          1> Sending: POST https://www.deutschlandcard.de/api/v1/auth/connect/token
20:56:37  1> Received: {"access_token":"eyJ[...and so on...]","expires_in":3600,"token_type":"Bearer","refresh_token":"43e[...and so on...]"}
          1> Lade Kontostand und Umsätze für DeutschlandCard ...
          1> Getting transactions since 9.9.2020...
          1> Sending: GET https://www.deutschlandcard.de/api/v1/profile/memberpoints
          1> Received: [...and so on...]
~~~

Apparently you did not receive other user feedback on this problem, so I may assume it was a local problem on my side. Many thanks for your time and for looking into it.

Please decide yourself to close this issue.

**Comment by markwiesemann** [comment]
Hi Andreas,
Thanks for the information. Unfortunately, I'm also affected by the problem since a few days. Not on every connect, but multiple times so far. I've added some debug code and directly afterwards the next connection to the DC server was successful. Therefore, I guess that your Mac will sooner or later also have problems again.
Most likely Google requires you and me to solve a real Captcha and it is not sufficient anymore to just load the Captcha code. If that's true, MoneyMoney would need an extension. MM's author already mentioned this last year when he made a small adjustment for the Captcha handling.
I'll do some further analyses and will to talk to the author.

**Comment by AndreasTusche** [comment]
Hi Mark, yes, your prognosis was right. The problem is 'back', or it never was gone? And it's like you said: not on every connect, but multiple times so far. It's not a big issue, since Deutschlandcard is only holding a few Euros but I like the idea to have such an overview included in MoneyMoney. Thanks for your efforts.

**Comment by markwiesemann** [comment]
I'll close this ticket as it is two years old. A weekly fetch (or even more often) works for me since quite a lot of time.

**Comment by markwiesemann** [comment]
I'll close this ticket as it is two years old. A weekly fetch (or even more often) works for me since quite a lot of time.
