### ISSUE TITLE
Fehler bei Kontoaktualisierung

### ISSUE THREAD

**Issue by UPKDev** [markwiesemann/moneymoney-deutschlandcard#2]
Bei der Kontoaktualisierung in MoneyMoney (MoneyMoney Version 2.4.19 Retail mit aktuellem Deutschlandcard-Lua-Script) gibt es seit kurzem eine Fehlermeldung mit der folgendem Inhalt:
"Der Server von DeutschlandCard hat kein Access-Token übermittelt. Bitte versuchen Sie es später noch einmal."
Kann das Deutschlandcard-Lua-Script entsprechend angepasst werden?

**Comment by markwiesemann** [comment]
Danke für die Meldung. Ich schaue, was ich tun kann.

**Comment by markwiesemann** [comment]
Ich habe den Abruf der Punkte inzwischen mehrmals ausprobiert: jedes Mal ohne Probleme.
Darf ich um einen Ausschnitt des Protokolls bitten? Möglicherweise handelt es sich um einen Folgefehler eines anderen Fehlers.

**Comment by UPKDev** [comment]
Ich kümmere mich darum, kann etwas dauern…

**Comment by UPKDev** [comment]
Vielen Dank für deine Mühe, der Fehler lag natürlich auf meiner Seite, die PIN wurde vom Server abgewiesen, nach dem Erstellen einer neuen PIN auf der Seite klappt der Abruf nun wieder! Ich wünsche frohe Festtage und einen guten Übergang ins neue Jahr!

**Comment by markwiesemann** [comment]
Danke für die nette Rückmeldung. Ebenfalls frohes Fest und einen guten Rutsch!
